# Generated by Django 4.2.16 on 2026-03-30 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_ciphertext', models.TextField(blank=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_used_at', models.DateTimeField(blank=True, null=True)),
                ('activation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('phone_edit_locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_profiles', to='properties.property')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tenant_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__full_name', 'id'],
            },
        ),
    ]
